[blackboard.urls]
login = "https://__-colaborador.blackboard.com/"
course_outline = "https://__.blackboard.com/ultra/courses/{id_interno}/outline"
api_memberships = "https://__.blackboard.com/learn/api/v1/users/{user_id}/memberships?expand=course&limit=10000"

[blackboard.selectors]
mfa_submit = "input#ContentPlaceHolder1_MFALoginControl1_RegistrationMethodView_btnSubmit"
user_input = "input[id$='txtUserid']"
pass_input = "input[id$='tbxPassword']"
login_btn = "input[id$='btnSubmit']"

[bot_files]
mapa_ids = "00_data/mapa_ids.csv"
chrome_profile = "01_input/chrome_profile"
parquet_file = "path/to/your/programacion.parquet"
